name: Assert Branch Naming Convention

on:
  pull_request:

jobs:
  branch-naming-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-branch-name@master
        with:
          regex: '([a-z])+\/([a-z]+-*[a-z]+)+' # Regex the branch should match.
          allowed_prefixes: 'feature,bugfix' # All branches should start with the given prefix
          ignore: main # Ignore exactly matching branch names from convention
          min_length: 3 # Min length of the branch name
          max_length: 64 # Max length of the branch name
